apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./docker-compose/docker-compose.services.yml -o ./k8s/
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: apigateway
  name: apigateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: apigateway
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./docker-compose/docker-compose.services.yml -o ./k8s/
        kompose.version: 1.38.0 (HEAD)
      labels:
        io.kompose.service: apigateway
    spec:
      containers:
        - env:
            - name: AUTH_SERVICE_URL
              value: http://authservice:8001
            - name: ORDER_SERVICE_URL
              value: http://orderservice:8003
            - name: PORT
              value: "8000"
            - name: PRODUCT_SERVICE_URL
              value: http://productservice:8002
          image: apigateway
          name: apigateway
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
