apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./docker-compose/docker-compose.services.yml -o ./k8s/
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: orderservice
  name: orderservice
spec:
  ports:
    - name: "8003"
      port: 8003
      targetPort: 8003
  selector:
    io.kompose.service: orderservice
