apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./docker-compose/docker-compose.services.yml -o ./k8s/
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: productservice
  name: productservice
spec:
  ports:
    - name: "8002"
      port: 8002
      targetPort: 8002
  selector:
    io.kompose.service: productservice
